### ISSUE TITLE
TYPO3 9 Support

### ISSUE THREAD

**Issue by StrikeAgainst** [franzholz/jfmulticontent#1]
Glad to see someone came back to continue development on this extension.
I've recently been tasked to upgrade an older Typo3 project from 6.2 to 9.5, together with all extensions where possible while replacing no-longer-supported ones. It uses this extension for rendering accordions, and I've been struggling to find a worthy replacement, nearly writing my own implementation via Mask.
Will this extension get an upgrade for 9.5 soon as well? That would actually save me a lot of work. Thank you a bunch. :-)

**Comment by franzholz** [comment]
I am still looking for a sponsor in order to make it also working under TYPO3 9.5 and even in 10.x. I hope that it will not take too long.

**Comment by franzholz** [comment]
jfmulticontent 2.11.0 works under TYPO3 9.5.
