### ISSUE TITLE
TYPO3 12

### ISSUE THREAD

**Issue by Epoche-Napoleon** [franzholz/jfmulticontent#13]
Now that support for TYPO3 9 and 10 has been discontinued and TYPO3 12 will be launched in a few days, I would like to know whether an update to the latest TYPO3 version is planned?

**Comment by franzholz** [comment]
Yes, an update for TYPO3 12 needs to be done.

**Comment by franzholz** [comment]
TYPO3 12 should be working now with the master branch.
