### ISSUE TITLE
'pages_language_overlay' doesn't exist

### ISSUE THREAD

**Issue by colaholiker** [franzholz/jfmulticontent#15]
An exception occurred while executing a query: Table 'pages_language_overlay' doesn't exist

Typo3 v12.4.13
jfmulticontent 2.15.1

Wed, 17 Apr 2024 11:59:08 +0200 [CRITICAL] request="f528c267f5b45" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB: FE): Doctrine\DBAL\Exception\TableNotFoundException, code #1146, file /kunden/179709_72070/rp-hosting/13/84/subdomains/pamas.20240408/typo3_src-12.4.13/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php, line 49: An exception occurred while executing a query: Table 'db179709_401.pages_language_overlay' doesn't exist - {"mode":"WEB","application_mode":"FE","exception_class":"Doctrine\\DBAL\\Exception\\TableNotFoundException","exception_code":1146,"file":"/kunden/179709_72070/rp-hosting/13/84/subdomains/pamas.20240408/typo3_src-12.4.13/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php","line":49,"message":"An exception occurred while executing a query: Table 'db179709_401.pages_language_overlay' doesn't exist","request_url":"https://pamas.dev-heindl.de/de/firmenprofil/messen","exception":null}

at TYPO3\CMS\Core\Database\Query\QueryBuilder->execute()
in /var/www/pamas.de.20240417/htdocs/typo3conf/ext/jfmulticontent/pi1/class.tx_jfmulticontent_pi1.php line 563

**Comment by franzholz** [comment]
Checkout the develop branch and tell me if this works!
