### ISSUE TITLE
PHP 8.2: Undefined array key "CONTENT"

### ISSUE THREAD

**Issue by aschmutt** [franzholz/jfmulticontent#24]
Error Message: Undefined array key "CONTENT" in 
/var/www/html/vendor/jambagecom/jfmulticontent/pi1/class.tx_jfmulticontent_pi1.php line 1572

Solution: initialize `$markerArray['CONTENT'] = ''`

TYPO3 Update to V12, PHP: 8.2

**Comment by aschmutt** [comment]
Patch file: 
[jfmulticontent_issue24.patch](https://github.com/user-attachments/files/18277692/jfmulticontent_issue24.patch)

Composer.json: 

"extra": {
    "patches": {
        "jambagecom/jfmulticontent": {
            "Issue23": "patches/jfmulticontent_issue23.patch"
        }
    }
},

**Comment by franzholz** [comment]
If possible, make a pull request next time.
