### ISSUE TITLE
Update Script Extensionmanager Error

### ISSUE THREAD

**Issue by christiana83** [franzholz/jfmulticontent#3]
hi!
the update script in extension manager throws the following error:

> Call to a member function fullQuoteStr() on null

how can I solve this issue to use the extension?

When not executing the update script the old frontend plugin (anythingslider) will throw an error

> Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::slashJS()

I am looking forward to get help from you!

greetings,
Christiana

**Comment by franzholz** [comment]
You must install the extension **typo3db_legacy** 1.1.1 !

**Comment by christiana83** [comment]
Thank you very much!!! I'll give it a try!

**Comment by christiana83** [comment]
Now, the script was running but in frontend I still get the message
	
Oops, an error occurred!
Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::slashJS()

**Comment by franzholz** [comment]
Replace the file pi1/class.tx_jfmulticontent_pi1.php with the Github version.

**Comment by christiana83** [comment]
perfect! now it works! many thanks!
