### ISSUE TITLE
Not yet fit for TYPO3 CMS 10

### ISSUE THREAD

**Issue by wazum** [franzholz/jfmulticontent#6]
After the installation (latest `dev-master`) I get the first error message:
 
```
Call to undefined method TYPO3\CMS\Core\Utility\GeneralUtility::devLog()
in /app/web/typo3conf/ext/jfmulticontent/pi1/class.tx_jfmulticontent_pi1.php line 1690
```

and in the backend, when editing a plugin of type jfmulticontent you get:

```
View [tx_jfmulticontent_view]
Unknown type: select, render type: select
```

Any roadmap when the extension will (really) work with TYPO3 CMS 10?

**Comment by franzholz** [comment]
Please test the new code.
