### ISSUE TITLE
$title is undefined

### ISSUE THREAD

**Issue by kosimas** [franzholz/jfmulticontent#7]
https://github.com/franzholz/jfmulticontent/blob/1e62cd09c831f496b7d3e4bee776feef020f1120/Classes/Updates/MigrateFlexformSheetIdentifierUpdate.php#L123

This line will result in an error in the upgrade wizard.
"Argument 1 passed to TYPO3\CMS\Install\Updates\Confirmation::__construct() must be of the type string, null given..."

**Comment by franzholz** [comment]
This issue is fixed now.
